using System;
using System.Collections.Generic;
using System.Linq;

namespace Standards.ISO3166.CountryCodes
{
    public partial class CountryCode
    {
        private static IReadOnlyCollection<CountryCode> CountryCodes { get; } = new List<CountryCode>
        {
            new CountryCode("AF", "AFG", 004, "Afghanistan"),
            new CountryCode("AX", "ALA", 248, "Åland Islands"),
            new CountryCode("AL", "ALB", 008, "Albania"),
            new CountryCode("DZ", "DZA", 012, "Algeria"),
            new CountryCode("AS", "ASM", 016, "American Samoa"),
            new CountryCode("AD", "AND", 020, "Andorra"),
            new CountryCode("AO", "AGO", 024, "Angola"),
            new CountryCode("AI", "AIA", 660, "Anguilla"),
            new CountryCode("AQ", "ATA", 010, "Antarctica"),
            new CountryCode("AG", "ATG", 028, "Antigua and Barbuda"),
            new CountryCode("AR", "ARG", 032, "Argentina"),
            new CountryCode("AM", "ARM", 051, "Armenia"),
            new CountryCode("AW", "ABW", 533, "Aruba"),
            new CountryCode("AU", "AUS", 036, "Australia"),
            new CountryCode("AT", "AUT", 040, "Austria"),
            new CountryCode("AZ", "AZE", 031, "Azerbaijan"),
            new CountryCode("BS", "BHS", 044, "Bahamas"),
            new CountryCode("BH", "BHR", 048, "Bahrain"),
            new CountryCode("BD", "BGD", 050, "Bangladesh"),
            new CountryCode("BB", "BRB", 052, "Barbados"),
            new CountryCode("BY", "BLR", 112, "Belarus"),
            new CountryCode("BE", "BEL", 056, "Belgium"),
            new CountryCode("BZ", "BLZ", 084, "Belize"),
            new CountryCode("BJ", "BEN", 204, "Benin"),
            new CountryCode("BM", "BMU", 060, "Bermuda"),
            new CountryCode("BT", "BTN", 064, "Bhutan"),
            new CountryCode("BO", "BOL", 068, "Bolivia, Plurinational State of"),
            new CountryCode("BQ", "BES", 535, "Bonaire, Sint Eustatius and Saba"),
            new CountryCode("BA", "BIH", 070, "Bosnia and Herzegovina"),
            new CountryCode("BW", "BWA", 072, "Botswana"),
            new CountryCode("BV", "BVT", 074, "Bouvet Island"),
            new CountryCode("BR", "BRA", 076, "Brazil"),
            new CountryCode("IO", "IOT", 086, "British Indian Ocean Territory"),
            new CountryCode("BN", "BRN", 096, "Brunei Darussalam"),
            new CountryCode("BG", "BGR", 100, "Bulgaria"),
            new CountryCode("BF", "BFA", 854, "Burkina Faso"),
            new CountryCode("BI", "BDI", 108, "Burundi"),
            new CountryCode("CV", "CPV", 132, "Cabo Verde"),
            new CountryCode("KH", "KHM", 116, "Cambodia"),
            new CountryCode("CM", "CMR", 120, "Cameroon"),
            new CountryCode("CA", "CAN", 124, "Canada"),
            new CountryCode("KY", "CYM", 136, "Cayman Islands"),
            new CountryCode("CF", "CAF", 140, "Central African Republic"),
            new CountryCode("TD", "TCD", 148, "Chad"),
            new CountryCode("CL", "CHL", 152, "Chile"),
            new CountryCode("CN", "CHN", 156, "China"),
            new CountryCode("CX", "CXR", 162, "Christmas Island"),
            new CountryCode("CC", "CCK", 166, "Cocos (Keeling) Islands"),
            new CountryCode("CO", "COL", 170, "Colombia"),
            new CountryCode("KM", "COM", 174, "Comoros"),
            new CountryCode("CG", "COG", 178, "Congo"),
            new CountryCode("CD", "COD", 180, "Congo, Democratic Republic of the"),
            new CountryCode("CK", "COK", 184, "Cook Islands"),
            new CountryCode("CR", "CRI", 188, "Costa Rica"),
            new CountryCode("CI", "CIV", 384, "Côte d'Ivoire"),
            new CountryCode("HR", "HRV", 191, "Croatia"),
            new CountryCode("CU", "CUB", 192, "Cuba"),
            new CountryCode("CW", "CUW", 531, "Curaçao"),
            new CountryCode("CY", "CYP", 196, "Cyprus"),
            new CountryCode("CZ", "CZE", 203, "Czechia"),
            new CountryCode("DK", "DNK", 208, "Denmark"),
            new CountryCode("DJ", "DJI", 262, "Djibouti"),
            new CountryCode("DM", "DMA", 212, "Dominica"),
            new CountryCode("DO", "DOM", 214, "Dominican Republic"),
            new CountryCode("EC", "ECU", 218, "Ecuador"),
            new CountryCode("EG", "EGY", 818, "Egypt"),
            new CountryCode("SV", "SLV", 222, "El Salvador"),
            new CountryCode("GQ", "GNQ", 226, "Equatorial Guinea"),
            new CountryCode("ER", "ERI", 232, "Eritrea"),
            new CountryCode("EE", "EST", 233, "Estonia"),
            new CountryCode("SZ", "SWZ", 748, "Eswatini"),
            new CountryCode("ET", "ETH", 231, "Ethiopia"),
            new CountryCode("FK", "FLK", 238, "Falkland Islands (Malvinas)"),
            new CountryCode("FO", "FRO", 234, "Faroe Islands"),
            new CountryCode("FJ", "FJI", 242, "Fiji"),
            new CountryCode("FI", "FIN", 246, "Finland"),
            new CountryCode("FR", "FRA", 250, "France"),
            new CountryCode("GF", "GUF", 254, "French Guiana"),
            new CountryCode("PF", "PYF", 258, "French Polynesia"),
            new CountryCode("TF", "ATF", 260, "French Southern Territories"),
            new CountryCode("GA", "GAB", 266, "Gabon"),
            new CountryCode("GM", "GMB", 270, "Gambia"),
            new CountryCode("GE", "GEO", 268, "Georgia"),
            new CountryCode("DE", "DEU", 276, "Germany"),
            new CountryCode("GH", "GHA", 288, "Ghana"),
            new CountryCode("GI", "GIB", 292, "Gibraltar"),
            new CountryCode("GR", "GRC", 300, "Greece"),
            new CountryCode("GL", "GRL", 304, "Greenland"),
            new CountryCode("GD", "GRD", 308, "Grenada"),
            new CountryCode("GP", "GLP", 312, "Guadeloupe"),
            new CountryCode("GU", "GUM", 316, "Guam"),
            new CountryCode("GT", "GTM", 320, "Guatemala"),
            new CountryCode("GG", "GGY", 831, "Guernsey"),
            new CountryCode("GN", "GIN", 324, "Guinea"),
            new CountryCode("GW", "GNB", 624, "Guinea-Bissau"),
            new CountryCode("GY", "GUY", 328, "Guyana"),
            new CountryCode("HT", "HTI", 332, "Haiti"),
            new CountryCode("HM", "HMD", 334, "Heard Island and McDonald Islands"),
            new CountryCode("VA", "VAT", 336, "Holy See"),
            new CountryCode("HN", "HND", 340, "Honduras"),
            new CountryCode("HK", "HKG", 344, "Hong Kong"),
            new CountryCode("HU", "HUN", 348, "Hungary"),
            new CountryCode("IS", "ISL", 352, "Iceland"),
            new CountryCode("IN", "IND", 356, "India"),
            new CountryCode("ID", "IDN", 360, "Indonesia"),
            new CountryCode("IR", "IRN", 364, "Iran, Islamic Republic of"),
            new CountryCode("IQ", "IRQ", 368, "Iraq"),
            new CountryCode("IE", "IRL", 372, "Ireland"),
            new CountryCode("IM", "IMN", 833, "Isle of Man"),
            new CountryCode("IL", "ISR", 376, "Israel"),
            new CountryCode("IT", "ITA", 380, "Italy"),
            new CountryCode("JM", "JAM", 388, "Jamaica"),
            new CountryCode("JP", "JPN", 392, "Japan"),
            new CountryCode("JE", "JEY", 832, "Jersey"),
            new CountryCode("JO", "JOR", 400, "Jordan"),
            new CountryCode("KZ", "KAZ", 398, "Kazakhstan"),
            new CountryCode("KE", "KEN", 404, "Kenya"),
            new CountryCode("KI", "KIR", 296, "Kiribati"),
            new CountryCode("KP", "PRK", 408, "Korea, Democratic People's Republic of"),
            new CountryCode("KR", "KOR", 410, "Korea, Republic of"),
            new CountryCode("KW", "KWT", 414, "Kuwait"),
            new CountryCode("KG", "KGZ", 417, "Kyrgyzstan"),
            new CountryCode("LA", "LAO", 418, "Lao People's Democratic Republic"),
            new CountryCode("LV", "LVA", 428, "Latvia"),
            new CountryCode("LB", "LBN", 422, "Lebanon"),
            new CountryCode("LS", "LSO", 426, "Lesotho"),
            new CountryCode("LR", "LBR", 430, "Liberia"),
            new CountryCode("LY", "LBY", 434, "Libya"),
            new CountryCode("LI", "LIE", 438, "Liechtenstein"),
            new CountryCode("LT", "LTU", 440, "Lithuania"),
            new CountryCode("LU", "LUX", 442, "Luxembourg"),
            new CountryCode("MO", "MAC", 446, "Macao"),
            new CountryCode("MG", "MDG", 450, "Madagascar"),
            new CountryCode("MW", "MWI", 454, "Malawi"),
            new CountryCode("MY", "MYS", 458, "Malaysia"),
            new CountryCode("MV", "MDV", 462, "Maldives"),
            new CountryCode("ML", "MLI", 466, "Mali"),
            new CountryCode("MT", "MLT", 470, "Malta"),
            new CountryCode("MH", "MHL", 584, "Marshall Islands"),
            new CountryCode("MQ", "MTQ", 474, "Martinique"),
            new CountryCode("MR", "MRT", 478, "Mauritania"),
            new CountryCode("MU", "MUS", 480, "Mauritius"),
            new CountryCode("YT", "MYT", 175, "Mayotte"),
            new CountryCode("MX", "MEX", 484, "Mexico"),
            new CountryCode("FM", "FSM", 583, "Micronesia, Federated States of"),
            new CountryCode("MD", "MDA", 498, "Moldova, Republic of"),
            new CountryCode("MC", "MCO", 492, "Monaco"),
            new CountryCode("MN", "MNG", 496, "Mongolia"),
            new CountryCode("ME", "MNE", 499, "Montenegro"),
            new CountryCode("MS", "MSR", 500, "Montserrat"),
            new CountryCode("MA", "MAR", 504, "Morocco"),
            new CountryCode("MZ", "MOZ", 508, "Mozambique"),
            new CountryCode("MM", "MMR", 104, "Myanmar"),
            new CountryCode("NA", "NAM", 516, "Namibia"),
            new CountryCode("NR", "NRU", 520, "Naoero"),
            new CountryCode("NP", "NPL", 524, "Nepal"),
            new CountryCode("NL", "NLD", 528, "Netherlands, Kingdom of the"),
            new CountryCode("NC", "NCL", 540, "New Caledonia"),
            new CountryCode("NZ", "NZL", 554, "New Zealand"),
            new CountryCode("NI", "NIC", 558, "Nicaragua"),
            new CountryCode("NE", "NER", 562, "Niger"),
            new CountryCode("NG", "NGA", 566, "Nigeria"),
            new CountryCode("NU", "NIU", 570, "Niue"),
            new CountryCode("NF", "NFK", 574, "Norfolk Island"),
            new CountryCode("MK", "MKD", 807, "North Macedonia"),
            new CountryCode("MP", "MNP", 580, "Northern Mariana Islands"),
            new CountryCode("NO", "NOR", 578, "Norway"),
            new CountryCode("OM", "OMN", 512, "Oman"),
            new CountryCode("PK", "PAK", 586, "Pakistan"),
            new CountryCode("PW", "PLW", 585, "Palau"),
            new CountryCode("PS", "PSE", 275, "Palestine, State of"),
            new CountryCode("PA", "PAN", 591, "Panama"),
            new CountryCode("PG", "PNG", 598, "Papua New Guinea"),
            new CountryCode("PY", "PRY", 600, "Paraguay"),
            new CountryCode("PE", "PER", 604, "Peru"),
            new CountryCode("PH", "PHL", 608, "Philippines"),
            new CountryCode("PN", "PCN", 612, "Pitcairn"),
            new CountryCode("PL", "POL", 616, "Poland"),
            new CountryCode("PT", "PRT", 620, "Portugal"),
            new CountryCode("PR", "PRI", 630, "Puerto Rico"),
            new CountryCode("QA", "QAT", 634, "Qatar"),
            new CountryCode("RE", "REU", 638, "Réunion"),
            new CountryCode("RO", "ROU", 642, "Romania"),
            new CountryCode("RU", "RUS", 643, "Russian Federation"),
            new CountryCode("RW", "RWA", 646, "Rwanda"),
            new CountryCode("BL", "BLM", 652, "Saint Barthélemy"),
            new CountryCode("SH", "SHN", 654, "Saint Helena, Ascension and Tristan da Cunha"),
            new CountryCode("KN", "KNA", 659, "Saint Kitts and Nevis"),
            new CountryCode("LC", "LCA", 662, "Saint Lucia"),
            new CountryCode("MF", "MAF", 663, "Saint Martin (French part)"),
            new CountryCode("PM", "SPM", 666, "Saint Pierre and Miquelon"),
            new CountryCode("VC", "VCT", 670, "Saint Vincent and the Grenadines"),
            new CountryCode("WS", "WSM", 882, "Samoa"),
            new CountryCode("SM", "SMR", 674, "San Marino"),
            new CountryCode("ST", "STP", 678, "Sao Tome and Principe"),
            new CountryCode("SA", "SAU", 682, "Saudi Arabia"),
            new CountryCode("SN", "SEN", 686, "Senegal"),
            new CountryCode("RS", "SRB", 688, "Serbia"),
            new CountryCode("SC", "SYC", 690, "Seychelles"),
            new CountryCode("SL", "SLE", 694, "Sierra Leone"),
            new CountryCode("SG", "SGP", 702, "Singapore"),
            new CountryCode("SX", "SXM", 534, "Sint Maarten (Dutch part)"),
            new CountryCode("SK", "SVK", 703, "Slovakia"),
            new CountryCode("SI", "SVN", 705, "Slovenia"),
            new CountryCode("SB", "SLB", 090, "Solomon Islands"),
            new CountryCode("SO", "SOM", 706, "Somalia"),
            new CountryCode("ZA", "ZAF", 710, "South Africa"),
            new CountryCode("GS", "SGS", 239, "South Georgia and the South Sandwich Islands"),
            new CountryCode("SS", "SSD", 728, "South Sudan"),
            new CountryCode("ES", "ESP", 724, "Spain"),
            new CountryCode("LK", "LKA", 144, "Sri Lanka"),
            new CountryCode("SD", "SDN", 729, "Sudan"),
            new CountryCode("SR", "SUR", 740, "Suriname"),
            new CountryCode("SJ", "SJM", 744, "Svalbard and Jan Mayen"),
            new CountryCode("SE", "SWE", 752, "Sweden"),
            new CountryCode("CH", "CHE", 756, "Switzerland"),
            new CountryCode("SY", "SYR", 760, "Syrian Arab Republic"),
            new CountryCode("TW", "TWN", 158, "Taiwan, Province of China"),
            new CountryCode("TJ", "TJK", 762, "Tajikistan"),
            new CountryCode("TZ", "TZA", 834, "Tanzania, United Republic of"),
            new CountryCode("TH", "THA", 764, "Thailand"),
            new CountryCode("TL", "TLS", 626, "Timor-Leste"),
            new CountryCode("TG", "TGO", 768, "Togo"),
            new CountryCode("TK", "TKL", 772, "Tokelau"),
            new CountryCode("TO", "TON", 776, "Tonga"),
            new CountryCode("TT", "TTO", 780, "Trinidad and Tobago"),
            new CountryCode("TN", "TUN", 788, "Tunisia"),
            new CountryCode("TR", "TUR", 792, "Türkiye"),
            new CountryCode("TM", "TKM", 795, "Turkmenistan"),
            new CountryCode("TC", "TCA", 796, "Turks and Caicos Islands"),
            new CountryCode("TV", "TUV", 798, "Tuvalu"),
            new CountryCode("UG", "UGA", 800, "Uganda"),
            new CountryCode("UA", "UKR", 804, "Ukraine"),
            new CountryCode("AE", "ARE", 784, "United Arab Emirates"),
            new CountryCode("GB", "GBR", 826, "United Kingdom of Great Britain and Northern Ireland"),
            new CountryCode("UM", "UMI", 581, "United States Minor Outlying Islands"),
            new CountryCode("US", "USA", 840, "United States of America"),
            new CountryCode("UY", "URY", 858, "Uruguay"),
            new CountryCode("UZ", "UZB", 860, "Uzbekistan"),
            new CountryCode("VU", "VUT", 548, "Vanuatu"),
            new CountryCode("VE", "VEN", 862, "Venezuela, Bolivarian Republic of"),
            new CountryCode("VN", "VNM", 704, "Viet Nam"),
            new CountryCode("VG", "VGB", 092, "Virgin Islands (British)"),
            new CountryCode("VI", "VIR", 850, "Virgin Islands (U.S.)"),
            new CountryCode("WF", "WLF", 876, "Wallis and Futuna"),
            new CountryCode("EH", "ESH", 732, "Western Sahara"),
            new CountryCode("YE", "YEM", 887, "Yemen"),
            new CountryCode("ZM", "ZMB", 894, "Zambia"),
            new CountryCode("ZW", "ZWE", 716, "Zimbabwe"),
        }.AsReadOnly();

        private static IReadOnlyDictionary<string, CountryCode> IndexByAlpha2 { get; } = CountryCodes.ToDictionary(_ => _.Alpha2, StringComparer.OrdinalIgnoreCase);

        private static IReadOnlyDictionary<string, CountryCode> IndexByAlpha3 { get; } = CountryCodes.ToDictionary(_ => _.Alpha3, StringComparer.OrdinalIgnoreCase);

        private static IReadOnlyDictionary<int, CountryCode> IndexByNumeric { get; } = CountryCodes.ToDictionary(_ => _.Numeric);
    }
}