<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputPath>$(SolutionDir)\Output\bin\$(Configuration)\$(AssemblyName)\</OutputPath>
    <IntermediateOutputPath>$(SolutionDir)\Output\obj\$(Configuration)\$(AssemblyName)\</IntermediateOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\AssemblyInfo.cs" Link="AssemblyInfo.cs" />
  </ItemGroup>

</Project>