name: Build & Tests

on:

  push:
    branches: [ "master", "develop" ]

  pull_request:
    branches: [ "master", "develop" ]
  
  workflow_dispatch:
  
  schedule:
        # Runs daily at 0:00 AM UTC
        - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      # Include for all branches and tags
      with:
          fetch-depth: 0
          
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
